# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfae935b026490ea6e0de4274b70a13ec86f3dc29bda0052e1c946ee772a84ae64e51de17bdc3c95a5324ea453dcfd47c75c7ce31d7fd962a84248f9c6052d69

test:
  secret_key_base: 37959247b6f05fe7789480433be9d458529ae311d4953ae49829ed6719cde66ba6f7842eff5e7434f419010ec026cf1c7145080d0a8eb995ccf5caf578c2b446

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
